### ISSUE TITLE
There seems to be a problem with gym0.19

### ISSUE THREAD

**Issue by jiabin-guo** [YanjieZe/rl3d#1]

**Comment by YanjieZe** [comment]
Hi,
Could you describe a bit more in detail?
Thanks!

**Comment by jiabin-guo** [comment]
Collecting gym==0.19.0
  Using cached gym-0.19.0.tar.gz (1.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by YanjieZe** [comment]
Could you try to download gym 0.19.0 and manually install it?
gym releases: https://github.com/openai/gym/releases
how to install: check their readme

**Comment by YanjieZe** [comment]
This seems to be a problem in setup.py. Maybe you need to fix the issue of this package by hand.

**Comment by jiabin-guo** [comment]
Thanks for your reply!This problem has been solved.
