### ISSUE TITLE
maybe something about the version of cython

### ISSUE THREAD

**Issue by jiabin-guo** [YanjieZe/rl3d#2]
the problem at the beginning:
  File "/home/loc/anaconda3/envs/rl3d-1/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /home/loc/anaconda3/envs/rl3d-1/lib/python3.8/site-packages/mujoco_py/cymj.pyx
then i change the version of cython,then other problems arise
and run bash script/train.py:
Compiling /home/loc/anaconda3/envs/rl3d-1/lib/python3.8/site-packages/mujoco_py/cymj.pyx because it changed.
[1/1] Cythonizing /home/loc/anaconda3/envs/rl3d-1/lib/python3.8/site-packages/mujoco_py/cymj.pyx
/home/loc/anaconda3/envs/rl3d-1/lib/python3.8/site-packages/mujoco_py/cymj.c:795:10: fatal error: mjmodel.h: 没有那个文件或目录
  795 | #include "mjmodel.h"
      |          ^~~~~~~~~~~
compilation terminated.

**Comment by YanjieZe** [comment]
Hi,
what is the cython version you are using?

maybe try this. 
```bash
pip install Cython==0.29.35
```
not sure whether this helps, but it helps in a lot of scenarios
