### ISSUE TITLE
Killed bash scripts/train.sh

### ISSUE THREAD

**Issue by nineman-YU** [YanjieZe/rl3d#3]
When I set up the environment and ran train.sh, the error shown below occurred at first.
![Screenshot from 2023-12-06 15-52-52](https://github.com/YanjieZe/rl3d/assets/144088285/a251e2ee-ca43-4f44-ad35-c9054f5b20b8)

And, when unset LD_PRELOAD was entered, the error shown in the following picture occurred. 
![Screenshot from 2023-12-06 15-53-22](https://github.com/YanjieZe/rl3d/assets/144088285/00dcaa19-769a-4549-a836-c2f2f2f2ab6d)

How can this be solved?

**Comment by YanjieZe** [comment]
Hi, could you give some info about your machine? such as GPU type, GPU memory, memory.
I am wondering whether this is from the not enough memory.

**Comment by nineman-YU** [comment]
Before posting an issue, I checked the GPU status with nvidia-smi and uploaded it because there were no problems. Through the reply, I also checked the CPU memory and confirmed that the problem was caused by the CPU.
By the way, aren't the simulator and train trained on GPU? Is it a problem with my settings?
I would appreciate your reply.

**Comment by YanjieZe** [comment]
I think both CPU and GPU should be used for the code. For the neural network inference, it is mainly on GPU. But the simulation would use CPU and GPU. For example, the rendering process could use GPU/CPU, and the simulation process mainly uses CPU in mujoco, as far as I know.
